name: my_portfolio
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  bloc: ^8.0.2
  cloud_firestore: ^3.1.10
  firebase: ^9.0.2
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.3.1
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  kartal: ^2.3.1
  url_launcher: ^6.0.20
  url_strategy: ^0.2.0

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
